<?php

namespace Database\Seeders;

use App\Models\DiklatRegistration;
use Illuminate\Database\Seeder;

class DiklatRegistrationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datas = [
            [
                'nama_lengkap' => 'R. AJ. NASYWAA TSAABITAH ARISANDY',
                'npm' => '24052010087',
                'fakultas' => 'Arsitektur dan Desain',
                'prodi' => 'DKV',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '85259171895',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Nadinda Khairunnisa Windajaya',
                'npm' => '24034010087',
                'fakultas' => 'FAKULTAS TEKNIK DAN SAINS',
                'prodi' => 'TEKNIK LINGKUNGAN',
                'spesifikasi' => ['vocal', 'guitar'],
                'no_telepon_pribadi' => '87854200017',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Putri Tanaya Honesty Aurellya',
                'npm' => '24043010100',
                'fakultas' => 'ilmu sosial dan ilmu politik',
                'prodi' => 'ilmu komunikasi',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '08880959280l',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'CHOIRUL WAHYU ADJI',
                'npm' => '24082010122',
                'fakultas' => 'ILMU KOMPUTER',
                'prodi' => 'SISTEM INFORMASI',
                'spesifikasi' => ['bass'],
                'no_telepon_pribadi' => '85259487706',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Zahlul Noer Laily',
                'npm' => '24082010163',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Sistem Informasi',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '85234187136',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Disain Ariesta Perdana Raharja',
                'npm' => '24081010321',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Informatika',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '81338512302',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'ISNA NUR RAHMAWATI',
                'npm' => '24041010141',
                'fakultas' => 'ilmu sosial dan ilmu politik',
                'prodi' => 'administrasi publik',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '82334110426',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Rahadyani Arafah Putri Sayoga',
                'npm' => '24013010240',
                'fakultas' => 'Ekonomi dan Bisnis',
                'prodi' => 'Akuntansi',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '81553702868',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'ANISYA DYAH AYU RAHMAWATI',
                'npm' => '24071010302',
                'fakultas' => 'HUKUM',
                'prodi' => 'HUKUM',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '81357617710',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Khansa Alyssa Fauziyah',
                'npm' => '24081010110',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Informatika',
                'spesifikasi' => ['keyboard'],
                'no_telepon_pribadi' => '85696101524',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Nadia Rahmi Zahara',
                'npm' => '24035010001',
                'fakultas' => 'Teknik dan Sains',
                'prodi' => 'Teknik Sipil',
                'spesifikasi' => ['guitar', 'bass'],
                'no_telepon_pribadi' => '085933026077',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Kelvin',
                'npm' => '23043010107',
                'fakultas' => 'Fisip',
                'prodi' => 'Ilkom',
                'spesifikasi' => ['vocal', 'guitar'],
                'no_telepon_pribadi' => '8816971516',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Jofanny Agnesy',
                'npm' => '24025010050',
                'fakultas' => 'Pertanian',
                'prodi' => 'Agroteknologi',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '82301964809',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'RR. ANINDYAH CHEASASILIA NANING',
                'npm' => '24012010236',
                'fakultas' => 'EKONOMI DAN BISNIS',
                'prodi' => 'MANAJEMEN',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '89687963806',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Nabila Aliya Khoirunnisa',
                'npm' => '24012010261',
                'fakultas' => 'Ekonomi dan Bisnis',
                'prodi' => 'Manajemen',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '83119980889',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Muhammad Syifa\' Habibillah',
                'npm' => '24091010029',
                'fakultas' => 'Kedokteran',
                'prodi' => 'Pendidikan dokter',
                'spesifikasi' => [],
                'no_telepon_pribadi' => '89542600001',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'NOVA AMALIA NOHARA',
                'npm' => '24041010172',
                'fakultas' => 'Ilmu sosial dan Ilmu Politik',
                'prodi' => 'Administrasi Publik',
                'spesifikasi' => ['vocal', 'guitar'],
                'no_telepon_pribadi' => '85730998389',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Sulthan wahyu atmodjo',
                'npm' => '24024010230',
                'fakultas' => 'Ekonomi Dan Bisnis',
                'prodi' => 'Agribisnis',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '82234592658',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Naura Aulia Zindra',
                'npm' => '24011010200',
                'fakultas' => 'Ekonomi',
                'prodi' => 'Ekonomi Pembangunan',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '87775787224',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Exellyana Rahmadani Damayanti',
                'npm' => '24071010306',
                'fakultas' => 'Hukum',
                'prodi' => 'Hukum',
                'spesifikasi' => ['keyboard'],
                'no_telepon_pribadi' => '82296624571',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Muhammad Riski Anandio',
                'npm' => '24012010449',
                'fakultas' => 'EKONOMI BISNIS',
                'prodi' => 'MANAJEMEN',
                'spesifikasi' => ['bass'],
                'no_telepon_pribadi' => '81230850704',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Moh.Alfin Setiawan',
                'npm' => '24035010093',
                'fakultas' => 'Teknik',
                'prodi' => 'Teknik Sipil',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '85708857761',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Angel Chataryna M',
                'npm' => '24041010325',
                'fakultas' => 'Fakultas ilmu sosial dan politik',
                'prodi' => 'Administrasi Publik',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '88102600001',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Naela Shafa Rania Putri',
                'npm' => '24071010038',
                'fakultas' => 'Hukum',
                'prodi' => 'Hukum',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '81218067853',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'olivia sativannisa',
                'npm' => '24043010260',
                'fakultas' => 'ilmu sosial dan politik',
                'prodi' => 'ilmu komunikasi',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '85259045506',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Muhammad Faiq Zaiimuddin',
                'npm' => '24014010109',
                'fakultas' => 'Ekonomi dan Bisnis',
                'prodi' => 'Kewirausahaan',
                'spesifikasi' => ['drum'],
                'no_telepon_pribadi' => '81336704496',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'YESSA ADELIA AGUSTIN',
                'npm' => '24042010122',
                'fakultas' => 'FAKULTAS ILMU SOSIAL DAN POLITIK',
                'prodi' => 'ADMINISTRASI BISNIS',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '85746671356',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Aliyah Shafa Nurhna',
                'npm' => '24043010101',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'prodi' => 'Ilmu Komunikasi',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '8128007309',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Aisyah Zahira Shofa',
                'npm' => '24033010087',
                'fakultas' => 'Fakultas Teknik dan Sains',
                'prodi' => 'Teknologi Pangan',
                'spesifikasi' => ['keyboard'],
                'no_telepon_pribadi' => '81515766249',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Joshua Kurniawan',
                'npm' => '24013010157',
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'prodi' => 'Akuntansi',
                'spesifikasi' => ['guitar', 'keyboard'],
                'no_telepon_pribadi' => '85159773035',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'theopilus sinuraya',
                'npm' => '22024010146',
                'fakultas' => 'pertanian',
                'prodi' => 'agribisnis',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '81262906564',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'BAGAS KUSUMA PRANATA',
                'npm' => '24035010007',
                'fakultas' => 'Teknik dan Sains',
                'prodi' => 'Teknik Sipil',
                'spesifikasi' => ['vocal', 'keyboard'],
                'no_telepon_pribadi' => '83832622701',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Dina Selomita',
                'npm' => '24042010223',
                'fakultas' => 'FISIP',
                'prodi' => 'Administrasi Bisnis',
                'spesifikasi' => ['keyboard'],
                'no_telepon_pribadi' => '85730446889',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Eileen Elyssia Moerdyanto',
                'npm' => '24043010176',
                'fakultas' => 'Ilmu Sosial dan Ilmu Politik',
                'prodi' => 'Ilmu Komunikasi',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '81332007361',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Mahendra Stevioly Putra',
                'npm' => '24082010079',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Sistem Informasi',
                'spesifikasi' => ['keyboard'],
                'no_telepon_pribadi' => '82230521051',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Cleo firman ferdinand',
                'npm' => '24081010173',
                'fakultas' => 'Ilmu komputer',
                'prodi' => 'Informatika',
                'spesifikasi' => ['vocal', 'bass'],
                'no_telepon_pribadi' => '81357602059',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Chelsea Naila Sanjaya',
                'npm' => '24011010187',
                'fakultas' => 'Ekonomi dan Bisnis',
                'prodi' => 'Ekonomi Pembangunan',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '85736844381',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Dian Alerti',
                'npm' => '24045010016',
                'fakultas' => 'Fakultas Ilmu Sosial Budaya Dan Politik',
                'prodi' => 'Pariwisata',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '85773169268',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Devan Aprila Cipta Rajasa',
                'npm' => '24036010068',
                'fakultas' => 'Teknik',
                'prodi' => 'Teknik Mesin',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '85335318746',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Arya Firmansyah Wicaksana',
                'npm' => '24031010015',
                'fakultas' => 'Teknik & Sains',
                'prodi' => 'Teknik Kimia',
                'spesifikasi' => ['guitar', 'bass', 'drum'],
                'no_telepon_pribadi' => '89530704666',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'ANDRE JOE PRASETYO',
                'npm' => '24071010231',
                'fakultas' => 'HUKUM',
                'prodi' => 'ILMU HUKUM',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '81234098164',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Ikhtiar Dimas Pradana',
                'npm' => '24033010142',
                'fakultas' => 'Teknik dan Sains',
                'prodi' => 'Teknologi Pangan',
                'spesifikasi' => ['guitar', 'drum'],
                'no_telepon_pribadi' => '81232863331',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Chrisena Arthaliando Putra',
                'npm' => '24031010240',
                'fakultas' => 'Fakultas Teknik Dan Sains',
                'prodi' => 'Teknik Kimia',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '81252371486',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Raveldo Andyka Ramadhan',
                'npm' => '24081010112',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Informatika',
                'spesifikasi' => ['keyboard'],
                'no_telepon_pribadi' => '85103220666',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'GALANG TERANG CHRISTIANO',
                'npm' => '24043010139',
                'fakultas' => 'FAKULTAS ILMU SOSIAL DAN ILMU POLITIK',
                'prodi' => 'ILMU KOMUNIKASI',
                'spesifikasi' => ['guitar', 'bass', 'keyboard', 'drum'],
                'no_telepon_pribadi' => '81339410269',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'BIMO ASTANTO ADJI',
                'npm' => '23013010325',
                'fakultas' => 'Ekonomi dan bisnis',
                'prodi' => 'Akuntansi',
                'spesifikasi' => [],
                'no_telepon_pribadi' => '85607688821',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Fachry Akbar Putra Ediesthia',
                'npm' => '24081010056',
                'fakultas' => 'Ilmu komputer',
                'prodi' => 'Informatika',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '81915150348',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Hylmi Tri Widiastoro',
                'npm' => '24032010028',
                'fakultas' => 'Teknik dan Sains',
                'prodi' => 'Teknik Industri',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '8953331000000',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Riski dwi ananda',
                'npm' => '24043010131',
                'fakultas' => 'Fakultas Ilmu Sosial dan Ilmu Politik',
                'prodi' => 'Ilmu Komunikasi',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '85233840804',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Michael Gideon Artanarga Pakpahan',
                'npm' => '24071010340',
                'fakultas' => 'Hukum',
                'prodi' => 'Ilmu Hukum',
                'spesifikasi' => ['bass', 'keyboard'],
                'no_telepon_pribadi' => '81266418480',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Renanti Putri Gunawan',
                'npm' => '24045010004',
                'fakultas' => 'Fakultas ilmu sosial dan ilmu politik',
                'prodi' => 'Pariwisata',
                'spesifikasi' => ['vocal', 'guitar'],
                'no_telepon_pribadi' => '85714244796',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Bagas Alif Marcellino',
                'npm' => '24043010300',
                'fakultas' => 'Ilmu Sosial dan Ilmu Politik',
                'prodi' => 'Ilmu Komunikasi',
                'spesifikasi' => ['vocal', 'drum'],
                'no_telepon_pribadi' => '81939457729',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'I Gst Ayu Nadya Savitri P. S',
                'npm' => '24071010211',
                'fakultas' => 'Hukum',
                'prodi' => 'Hukum',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '82230119271',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Muhammad Bintang Naufal',
                'npm' => '24081010138',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Informatika',
                'spesifikasi' => ['guitar', 'bass'],
                'no_telepon_pribadi' => '83192812629',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Maya Aksa Fibellanindy',
                'npm' => '24081010221',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Informatika',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '87888557433',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Hangesthi Martha Widhi Wicakseni',
                'npm' => '24035010021',
                'fakultas' => 'Teknik dan Sains',
                'prodi' => 'Teknik Sipil',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '81234553091',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Fauzan Rahmatullah',
                'npm' => '24081010030',
                'fakultas' => 'Fakultas Ilmu Komputer',
                'prodi' => 'Informatika',
                'spesifikasi' => ['guitar', 'bass'],
                'no_telepon_pribadi' => '85850801262',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Sarah Azzakiyyah Hasan',
                'npm' => '24052010005',
                'fakultas' => 'Fakultas Arsitektur dan Desain',
                'prodi' => 'DKV',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '81357211982',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'WISANGGENI ARRIZAL SHALIKHIN',
                'npm' => '24071010322',
                'fakultas' => 'HUKUM',
                'prodi' => 'HUKUM',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '81216972360',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'SATRIA ALANKU YUDHITA PUTRA',
                'npm' => '24045010050',
                'fakultas' => 'Ilmu Sosial dan Ilmu Politik',
                'prodi' => 'Pariwisata',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '89685642314',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Raditya Bhramanta',
                'npm' => '24052010044',
                'fakultas' => 'Fakultas Arsitektur dan Desain',
                'prodi' => 'Desain Komunikasi Visual',
                'spesifikasi' => ['guitar', 'bass'],
                'no_telepon_pribadi' => '81216058359',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Izzati Kamila Putri',
                'npm' => '24083010059',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Sains Data',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '81331811745',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Mirza Ramadian Raffa',
                'npm' => '24082010241',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Sistem Informasi',
                'spesifikasi' => ['vocal', 'drum'],
                'no_telepon_pribadi' => '81336831221',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Muhamad Haikal Nauvaldi',
                'npm' => '24032010168',
                'fakultas' => 'Fakultas teknik dan sains',
                'prodi' => 'Teknik Industri',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '85932940296',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Muhammad Rakha Firmansyah',
                'npm' => '24012010198',
                'fakultas' => 'Ekonomi dan Bisnis',
                'prodi' => 'Manajemen',
                'spesifikasi' => ['keyboard'],
                'no_telepon_pribadi' => '87856439906',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Nindya Pramana',
                'npm' => '24081010197',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Informatika',
                'spesifikasi' => ['guitar', 'bass', 'keyboard'],
                'no_telepon_pribadi' => '85155446285',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Hangesti intan hartanto',
                'npm' => '24013010059',
                'fakultas' => 'Ekonomi bisnis',
                'prodi' => 'Akuntansi',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '81228268504',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Fadhil Rahman Agustien',
                'npm' => '24035010048',
                'fakultas' => 'Teknik',
                'prodi' => 'Teknik Sipil',
                'spesifikasi' => ['guitar', 'bass'],
                'no_telepon_pribadi' => '85559639054',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Romi Rafael',
                'npm' => '23052010103',
                'fakultas' => 'Fakultas Arsitektur dan Desain',
                'prodi' => 'DKV',
                'spesifikasi' => ['drum'],
                'no_telepon_pribadi' => '82242593941',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'VINA DWI MAULITA',
                'npm' => '24082010074',
                'fakultas' => 'ILMU KOMPUTER',
                'prodi' => 'SISTEM INFORMASI',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '6281393501415',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Stevan Agustin Purba',
                'npm' => '24082010156',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Sistem Informasi',
                'spesifikasi' => ['bass', 'keyboard'],
                'no_telepon_pribadi' => '85664412254',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Samuel Thyago Pangaribuan',
                'npm' => '24032010145',
                'fakultas' => 'Teknik dan Sains',
                'prodi' => 'Teknik Industri',
                'spesifikasi' => ['keyboard'],
                'no_telepon_pribadi' => '81358059183',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Mochammad Kevin Ubaidillah',
                'npm' => '24033010073',
                'fakultas' => 'Fakultas teknik dan sains',
                'prodi' => 'Teknologi Pangan',
                'spesifikasi' => ['guitar', 'drum'],
                'no_telepon_pribadi' => '87777303057',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Rinna Santiana Agung',
                'npm' => '24042010046',
                'fakultas' => 'Ilmu Sosial dan Ilmu Politik',
                'prodi' => 'Administrasi Bisnis',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '8993771827',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Nasya Alriani Lamarta',
                'npm' => '24084010033',
                'fakultas' => 'Ilmu Komputer',
                'prodi' => 'Bisnis Digital',
                'spesifikasi' => ['vocal', 'drum'],
                'no_telepon_pribadi' => '85883556221',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'ARIFUDIN MAUNILLAH MUHAMAD',
                'npm' => '23025010068',
                'fakultas' => 'PERTANIAN',
                'prodi' => 'AGROTEKNOLOGI',
                'spesifikasi' => ['drum'],
                'no_telepon_pribadi' => '82324117298',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'NAZWA PUTRI DITI',
                'npm' => '24032010205',
                'fakultas' => 'TEKNIK & SAINS',
                'prodi' => 'TEKNIK INDUSTRI',
                'spesifikasi' => ['guitar'],
                'no_telepon_pribadi' => '85733059819',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Keyshita Armevia',
                'npm' => '24044010092',
                'fakultas' => 'Fakultas Ilmu Sosial dan Ilmu Politik',
                'prodi' => 'Hubungan Internasional',
                'spesifikasi' => ['keyboard'],
                'no_telepon_pribadi' => '81330660541',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Maulana Akbar Indra',
                'npm' => '24084010044',
                'fakultas' => 'Fakultas Ilmu Komputer',
                'prodi' => 'Bisnis Digital',
                'spesifikasi' => ['drum'],
                'no_telepon_pribadi' => '81231843586',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Eunike Naema Simbolon',
                'npm' => '24013010097',
                'fakultas' => 'Ekonomi dan Bisnis',
                'prodi' => 'Akuntansi',
                'spesifikasi' => ['vocal'],
                'no_telepon_pribadi' => '8953390000000',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'perempuan',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
            [
                'nama_lengkap' => 'Michael Tobias Reynaldo Wibowo',
                'npm' => '24071010037',
                'fakultas' => 'Hukum',
                'prodi' => 'Hukum',
                'spesifikasi' => ['vocal','guitar'],
                'no_telepon_pribadi' => '82236400046',
                'no_telepon_ortu' => null,
                'jenis_kelamin' => 'laki-laki',
                'riwayat_penyakit' => null,
                'riwayat_alergi' => null,
            ],
        ];

        foreach ($datas as $data) {
            $data['diklat_period_id'] = 2;
            $data['status'] = 'approved';
            DiklatRegistration::create($data);
        }
    }
}
